package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmActStl;
import common.repository.hmfs.model.HmActStlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmActStlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int countByExample(HmActStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int deleteByExample(HmActStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int insert(HmActStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int insertSelective(HmActStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    List<HmActStl> selectByExample(HmActStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    HmActStl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmActStl record, @Param("example") HmActStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int updateByExample(@Param("record") HmActStl record, @Param("example") HmActStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int updateByPrimaryKeySelective(HmActStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_STL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    int updateByPrimaryKey(HmActStl record);
}