package common.repository.hmfs.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TxnCbsLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public TxnCbsLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTxnSnIsNull() {
            addCriterion("TXN_SN is null");
            return (Criteria) this;
        }

        public Criteria andTxnSnIsNotNull() {
            addCriterion("TXN_SN is not null");
            return (Criteria) this;
        }

        public Criteria andTxnSnEqualTo(String value) {
            addCriterion("TXN_SN =", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotEqualTo(String value) {
            addCriterion("TXN_SN <>", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnGreaterThan(String value) {
            addCriterion("TXN_SN >", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_SN >=", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLessThan(String value) {
            addCriterion("TXN_SN <", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLessThanOrEqualTo(String value) {
            addCriterion("TXN_SN <=", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLike(String value) {
            addCriterion("TXN_SN like", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotLike(String value) {
            addCriterion("TXN_SN not like", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnIn(List<String> values) {
            addCriterion("TXN_SN in", values, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotIn(List<String> values) {
            addCriterion("TXN_SN not in", values, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnBetween(String value1, String value2) {
            addCriterion("TXN_SN between", value1, value2, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotBetween(String value1, String value2) {
            addCriterion("TXN_SN not between", value1, value2, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIsNull() {
            addCriterion("TXN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIsNotNull() {
            addCriterion("TXN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andTxnTimeEqualTo(String value) {
            addCriterion("TXN_TIME =", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotEqualTo(String value) {
            addCriterion("TXN_TIME <>", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeGreaterThan(String value) {
            addCriterion("TXN_TIME >", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_TIME >=", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLessThan(String value) {
            addCriterion("TXN_TIME <", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLessThanOrEqualTo(String value) {
            addCriterion("TXN_TIME <=", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeLike(String value) {
            addCriterion("TXN_TIME like", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotLike(String value) {
            addCriterion("TXN_TIME not like", value, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeIn(List<String> values) {
            addCriterion("TXN_TIME in", values, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotIn(List<String> values) {
            addCriterion("TXN_TIME not in", values, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeBetween(String value1, String value2) {
            addCriterion("TXN_TIME between", value1, value2, "txnTime");
            return (Criteria) this;
        }

        public Criteria andTxnTimeNotBetween(String value1, String value2) {
            addCriterion("TXN_TIME not between", value1, value2, "txnTime");
            return (Criteria) this;
        }

        public Criteria andFundActnoIsNull() {
            addCriterion("FUND_ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andFundActnoIsNotNull() {
            addCriterion("FUND_ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andFundActnoEqualTo(String value) {
            addCriterion("FUND_ACTNO =", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoNotEqualTo(String value) {
            addCriterion("FUND_ACTNO <>", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoGreaterThan(String value) {
            addCriterion("FUND_ACTNO >", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_ACTNO >=", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoLessThan(String value) {
            addCriterion("FUND_ACTNO <", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoLessThanOrEqualTo(String value) {
            addCriterion("FUND_ACTNO <=", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoLike(String value) {
            addCriterion("FUND_ACTNO like", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoNotLike(String value) {
            addCriterion("FUND_ACTNO not like", value, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoIn(List<String> values) {
            addCriterion("FUND_ACTNO in", values, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoNotIn(List<String> values) {
            addCriterion("FUND_ACTNO not in", values, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoBetween(String value1, String value2) {
            addCriterion("FUND_ACTNO between", value1, value2, "fundActno");
            return (Criteria) this;
        }

        public Criteria andFundActnoNotBetween(String value1, String value2) {
            addCriterion("FUND_ACTNO not between", value1, value2, "fundActno");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNull() {
            addCriterion("TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNotNull() {
            addCriterion("TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeEqualTo(String value) {
            addCriterion("TXN_CODE =", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotEqualTo(String value) {
            addCriterion("TXN_CODE <>", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThan(String value) {
            addCriterion("TXN_CODE >", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_CODE >=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThan(String value) {
            addCriterion("TXN_CODE <", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_CODE <=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLike(String value) {
            addCriterion("TXN_CODE like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotLike(String value) {
            addCriterion("TXN_CODE not like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIn(List<String> values) {
            addCriterion("TXN_CODE in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotIn(List<String> values) {
            addCriterion("TXN_CODE not in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeBetween(String value1, String value2) {
            addCriterion("TXN_CODE between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_CODE not between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andMesgNoIsNull() {
            addCriterion("MESG_NO is null");
            return (Criteria) this;
        }

        public Criteria andMesgNoIsNotNull() {
            addCriterion("MESG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMesgNoEqualTo(String value) {
            addCriterion("MESG_NO =", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoNotEqualTo(String value) {
            addCriterion("MESG_NO <>", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoGreaterThan(String value) {
            addCriterion("MESG_NO >", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoGreaterThanOrEqualTo(String value) {
            addCriterion("MESG_NO >=", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoLessThan(String value) {
            addCriterion("MESG_NO <", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoLessThanOrEqualTo(String value) {
            addCriterion("MESG_NO <=", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoLike(String value) {
            addCriterion("MESG_NO like", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoNotLike(String value) {
            addCriterion("MESG_NO not like", value, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoIn(List<String> values) {
            addCriterion("MESG_NO in", values, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoNotIn(List<String> values) {
            addCriterion("MESG_NO not in", values, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoBetween(String value1, String value2) {
            addCriterion("MESG_NO between", value1, value2, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andMesgNoNotBetween(String value1, String value2) {
            addCriterion("MESG_NO not between", value1, value2, "mesgNo");
            return (Criteria) this;
        }

        public Criteria andOpacBridIsNull() {
            addCriterion("OPAC_BRID is null");
            return (Criteria) this;
        }

        public Criteria andOpacBridIsNotNull() {
            addCriterion("OPAC_BRID is not null");
            return (Criteria) this;
        }

        public Criteria andOpacBridEqualTo(String value) {
            addCriterion("OPAC_BRID =", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotEqualTo(String value) {
            addCriterion("OPAC_BRID <>", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridGreaterThan(String value) {
            addCriterion("OPAC_BRID >", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridGreaterThanOrEqualTo(String value) {
            addCriterion("OPAC_BRID >=", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLessThan(String value) {
            addCriterion("OPAC_BRID <", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLessThanOrEqualTo(String value) {
            addCriterion("OPAC_BRID <=", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridLike(String value) {
            addCriterion("OPAC_BRID like", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotLike(String value) {
            addCriterion("OPAC_BRID not like", value, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridIn(List<String> values) {
            addCriterion("OPAC_BRID in", values, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotIn(List<String> values) {
            addCriterion("OPAC_BRID not in", values, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridBetween(String value1, String value2) {
            addCriterion("OPAC_BRID between", value1, value2, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andOpacBridNotBetween(String value1, String value2) {
            addCriterion("OPAC_BRID not between", value1, value2, "opacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNull() {
            addCriterion("TXAC_BRID is null");
            return (Criteria) this;
        }

        public Criteria andTxacBridIsNotNull() {
            addCriterion("TXAC_BRID is not null");
            return (Criteria) this;
        }

        public Criteria andTxacBridEqualTo(String value) {
            addCriterion("TXAC_BRID =", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotEqualTo(String value) {
            addCriterion("TXAC_BRID <>", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThan(String value) {
            addCriterion("TXAC_BRID >", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridGreaterThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID >=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThan(String value) {
            addCriterion("TXAC_BRID <", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLessThanOrEqualTo(String value) {
            addCriterion("TXAC_BRID <=", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridLike(String value) {
            addCriterion("TXAC_BRID like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotLike(String value) {
            addCriterion("TXAC_BRID not like", value, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridIn(List<String> values) {
            addCriterion("TXAC_BRID in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotIn(List<String> values) {
            addCriterion("TXAC_BRID not in", values, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridBetween(String value1, String value2) {
            addCriterion("TXAC_BRID between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andTxacBridNotBetween(String value1, String value2) {
            addCriterion("TXAC_BRID not between", value1, value2, "txacBrid");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoIsNull() {
            addCriterion("CBS_ACCTNO is null");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoIsNotNull() {
            addCriterion("CBS_ACCTNO is not null");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoEqualTo(String value) {
            addCriterion("CBS_ACCTNO =", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoNotEqualTo(String value) {
            addCriterion("CBS_ACCTNO <>", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoGreaterThan(String value) {
            addCriterion("CBS_ACCTNO >", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoGreaterThanOrEqualTo(String value) {
            addCriterion("CBS_ACCTNO >=", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoLessThan(String value) {
            addCriterion("CBS_ACCTNO <", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoLessThanOrEqualTo(String value) {
            addCriterion("CBS_ACCTNO <=", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoLike(String value) {
            addCriterion("CBS_ACCTNO like", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoNotLike(String value) {
            addCriterion("CBS_ACCTNO not like", value, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoIn(List<String> values) {
            addCriterion("CBS_ACCTNO in", values, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoNotIn(List<String> values) {
            addCriterion("CBS_ACCTNO not in", values, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoBetween(String value1, String value2) {
            addCriterion("CBS_ACCTNO between", value1, value2, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andCbsAcctnoNotBetween(String value1, String value2) {
            addCriterion("CBS_ACCTNO not between", value1, value2, "cbsAcctno");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNull() {
            addCriterion("TXN_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIsNotNull() {
            addCriterion("TXN_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTxnAmtEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT =", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <>", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThan(BigDecimal value) {
            addCriterion("TXN_AMT >", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT >=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThan(BigDecimal value) {
            addCriterion("TXN_AMT <", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TXN_AMT <=", value, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotIn(List<BigDecimal> values) {
            addCriterion("TXN_AMT not in", values, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andTxnAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TXN_AMT not between", value1, value2, "txnAmt");
            return (Criteria) this;
        }

        public Criteria andDcFlagIsNull() {
            addCriterion("DC_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDcFlagIsNotNull() {
            addCriterion("DC_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDcFlagEqualTo(String value) {
            addCriterion("DC_FLAG =", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagNotEqualTo(String value) {
            addCriterion("DC_FLAG <>", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagGreaterThan(String value) {
            addCriterion("DC_FLAG >", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DC_FLAG >=", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagLessThan(String value) {
            addCriterion("DC_FLAG <", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagLessThanOrEqualTo(String value) {
            addCriterion("DC_FLAG <=", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagLike(String value) {
            addCriterion("DC_FLAG like", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagNotLike(String value) {
            addCriterion("DC_FLAG not like", value, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagIn(List<String> values) {
            addCriterion("DC_FLAG in", values, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagNotIn(List<String> values) {
            addCriterion("DC_FLAG not in", values, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagBetween(String value1, String value2) {
            addCriterion("DC_FLAG between", value1, value2, "dcFlag");
            return (Criteria) this;
        }

        public Criteria andDcFlagNotBetween(String value1, String value2) {
            addCriterion("DC_FLAG not between", value1, value2, "dcFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 11 11:38:24 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 11:38:24 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}