package common.repository.hmfs.model;

public class BkCmbDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.BK_CMB_DEPT.PKID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.BK_CMB_DEPT.BK_DEPT_ID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    private String bkDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.BK_CMB_DEPT.BK_DEPT_NAME
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    private String bkDeptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.BK_CMB_DEPT.REMARK
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.BK_CMB_DEPT.PKID
     *
     * @return the value of HMFS.BK_CMB_DEPT.PKID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.BK_CMB_DEPT.PKID
     *
     * @param pkid the value for HMFS.BK_CMB_DEPT.PKID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.BK_CMB_DEPT.BK_DEPT_ID
     *
     * @return the value of HMFS.BK_CMB_DEPT.BK_DEPT_ID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public String getBkDeptId() {
        return bkDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.BK_CMB_DEPT.BK_DEPT_ID
     *
     * @param bkDeptId the value for HMFS.BK_CMB_DEPT.BK_DEPT_ID
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public void setBkDeptId(String bkDeptId) {
        this.bkDeptId = bkDeptId == null ? null : bkDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.BK_CMB_DEPT.BK_DEPT_NAME
     *
     * @return the value of HMFS.BK_CMB_DEPT.BK_DEPT_NAME
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public String getBkDeptName() {
        return bkDeptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.BK_CMB_DEPT.BK_DEPT_NAME
     *
     * @param bkDeptName the value for HMFS.BK_CMB_DEPT.BK_DEPT_NAME
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public void setBkDeptName(String bkDeptName) {
        this.bkDeptName = bkDeptName == null ? null : bkDeptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.BK_CMB_DEPT.REMARK
     *
     * @return the value of HMFS.BK_CMB_DEPT.REMARK
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.BK_CMB_DEPT.REMARK
     *
     * @param remark the value for HMFS.BK_CMB_DEPT.REMARK
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}