package common.repository.hmfs.model;

import java.math.BigDecimal;

public class HmActStl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.PKID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.BRANCH_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.BANK_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNO
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String cbsActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String cbsActname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.CBS_ACTTYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String cbsActtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.DEPOSIT_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String depositType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.ORG_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.ORG_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.ORG_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTNO1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String settleActno1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTTYPE1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String settleActtype1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.ACT_STS
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String actSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal actBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.INTC_PDT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal intcPdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.LAST_TXN_DT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String lastTxnDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.LAST_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal lastActBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.OPEN_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String openActDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.CLOSE_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String closeActDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.FRZ_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String frzActDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.INIT_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal initActBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.INT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal intAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.INCR_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal incrAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.OTH_IN_AM
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal othInAm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.AGN_IN_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal agnInAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal outAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.INCR_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal incrOutAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.OTH_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private BigDecimal othOutAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.REMARK
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_ACTINFO_CBS.RECVERSION
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    private Integer recversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.PKID
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.PKID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.PKID
     *
     * @param pkid the value for HMFS.HM_ACTINFO_CBS.PKID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.BRANCH_ID
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.BRANCH_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.BRANCH_ID
     *
     * @param branchId the value for HMFS.HM_ACTINFO_CBS.BRANCH_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.BANK_NAME
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.BANK_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.BANK_NAME
     *
     * @param bankName the value for HMFS.HM_ACTINFO_CBS.BANK_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNO
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.CBS_ACTNO
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getCbsActno() {
        return cbsActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNO
     *
     * @param cbsActno the value for HMFS.HM_ACTINFO_CBS.CBS_ACTNO
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setCbsActno(String cbsActno) {
        this.cbsActno = cbsActno == null ? null : cbsActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNAME
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.CBS_ACTNAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getCbsActname() {
        return cbsActname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTNAME
     *
     * @param cbsActname the value for HMFS.HM_ACTINFO_CBS.CBS_ACTNAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setCbsActname(String cbsActname) {
        this.cbsActname = cbsActname == null ? null : cbsActname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTTYPE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.CBS_ACTTYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getCbsActtype() {
        return cbsActtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.CBS_ACTTYPE
     *
     * @param cbsActtype the value for HMFS.HM_ACTINFO_CBS.CBS_ACTTYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setCbsActtype(String cbsActtype) {
        this.cbsActtype = cbsActtype == null ? null : cbsActtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.DEPOSIT_TYPE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.DEPOSIT_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getDepositType() {
        return depositType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.DEPOSIT_TYPE
     *
     * @param depositType the value for HMFS.HM_ACTINFO_CBS.DEPOSIT_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setDepositType(String depositType) {
        this.depositType = depositType == null ? null : depositType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.ORG_ID
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.ORG_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.ORG_ID
     *
     * @param orgId the value for HMFS.HM_ACTINFO_CBS.ORG_ID
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.ORG_TYPE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.ORG_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.ORG_TYPE
     *
     * @param orgType the value for HMFS.HM_ACTINFO_CBS.ORG_TYPE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType == null ? null : orgType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.ORG_NAME
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.ORG_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.ORG_NAME
     *
     * @param orgName the value for HMFS.HM_ACTINFO_CBS.ORG_NAME
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTNO1
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.SETTLE_ACTNO1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getSettleActno1() {
        return settleActno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTNO1
     *
     * @param settleActno1 the value for HMFS.HM_ACTINFO_CBS.SETTLE_ACTNO1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setSettleActno1(String settleActno1) {
        this.settleActno1 = settleActno1 == null ? null : settleActno1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTTYPE1
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.SETTLE_ACTTYPE1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getSettleActtype1() {
        return settleActtype1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.SETTLE_ACTTYPE1
     *
     * @param settleActtype1 the value for HMFS.HM_ACTINFO_CBS.SETTLE_ACTTYPE1
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setSettleActtype1(String settleActtype1) {
        this.settleActtype1 = settleActtype1 == null ? null : settleActtype1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.ACT_STS
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.ACT_STS
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getActSts() {
        return actSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.ACT_STS
     *
     * @param actSts the value for HMFS.HM_ACTINFO_CBS.ACT_STS
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setActSts(String actSts) {
        this.actSts = actSts == null ? null : actSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.ACT_BAL
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getActBal() {
        return actBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.ACT_BAL
     *
     * @param actBal the value for HMFS.HM_ACTINFO_CBS.ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setActBal(BigDecimal actBal) {
        this.actBal = actBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.INTC_PDT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.INTC_PDT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getIntcPdt() {
        return intcPdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.INTC_PDT
     *
     * @param intcPdt the value for HMFS.HM_ACTINFO_CBS.INTC_PDT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setIntcPdt(BigDecimal intcPdt) {
        this.intcPdt = intcPdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.LAST_TXN_DT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.LAST_TXN_DT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getLastTxnDt() {
        return lastTxnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.LAST_TXN_DT
     *
     * @param lastTxnDt the value for HMFS.HM_ACTINFO_CBS.LAST_TXN_DT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setLastTxnDt(String lastTxnDt) {
        this.lastTxnDt = lastTxnDt == null ? null : lastTxnDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.LAST_ACT_BAL
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.LAST_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getLastActBal() {
        return lastActBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.LAST_ACT_BAL
     *
     * @param lastActBal the value for HMFS.HM_ACTINFO_CBS.LAST_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setLastActBal(BigDecimal lastActBal) {
        this.lastActBal = lastActBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.OPEN_ACT_DATE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.OPEN_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getOpenActDate() {
        return openActDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.OPEN_ACT_DATE
     *
     * @param openActDate the value for HMFS.HM_ACTINFO_CBS.OPEN_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOpenActDate(String openActDate) {
        this.openActDate = openActDate == null ? null : openActDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.CLOSE_ACT_DATE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.CLOSE_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getCloseActDate() {
        return closeActDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.CLOSE_ACT_DATE
     *
     * @param closeActDate the value for HMFS.HM_ACTINFO_CBS.CLOSE_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setCloseActDate(String closeActDate) {
        this.closeActDate = closeActDate == null ? null : closeActDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.FRZ_ACT_DATE
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.FRZ_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getFrzActDate() {
        return frzActDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.FRZ_ACT_DATE
     *
     * @param frzActDate the value for HMFS.HM_ACTINFO_CBS.FRZ_ACT_DATE
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setFrzActDate(String frzActDate) {
        this.frzActDate = frzActDate == null ? null : frzActDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.INIT_ACT_BAL
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.INIT_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getInitActBal() {
        return initActBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.INIT_ACT_BAL
     *
     * @param initActBal the value for HMFS.HM_ACTINFO_CBS.INIT_ACT_BAL
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setInitActBal(BigDecimal initActBal) {
        this.initActBal = initActBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.INT_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.INT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getIntAmt() {
        return intAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.INT_AMT
     *
     * @param intAmt the value for HMFS.HM_ACTINFO_CBS.INT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setIntAmt(BigDecimal intAmt) {
        this.intAmt = intAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.INCR_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.INCR_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getIncrAmt() {
        return incrAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.INCR_AMT
     *
     * @param incrAmt the value for HMFS.HM_ACTINFO_CBS.INCR_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setIncrAmt(BigDecimal incrAmt) {
        this.incrAmt = incrAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.OTH_IN_AM
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.OTH_IN_AM
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getOthInAm() {
        return othInAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.OTH_IN_AM
     *
     * @param othInAm the value for HMFS.HM_ACTINFO_CBS.OTH_IN_AM
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOthInAm(BigDecimal othInAm) {
        this.othInAm = othInAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.AGN_IN_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.AGN_IN_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getAgnInAmt() {
        return agnInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.AGN_IN_AMT
     *
     * @param agnInAmt the value for HMFS.HM_ACTINFO_CBS.AGN_IN_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setAgnInAmt(BigDecimal agnInAmt) {
        this.agnInAmt = agnInAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.OUT_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getOutAmt() {
        return outAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.OUT_AMT
     *
     * @param outAmt the value for HMFS.HM_ACTINFO_CBS.OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOutAmt(BigDecimal outAmt) {
        this.outAmt = outAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.INCR_OUT_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.INCR_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getIncrOutAmt() {
        return incrOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.INCR_OUT_AMT
     *
     * @param incrOutAmt the value for HMFS.HM_ACTINFO_CBS.INCR_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setIncrOutAmt(BigDecimal incrOutAmt) {
        this.incrOutAmt = incrOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.OTH_OUT_AMT
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.OTH_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public BigDecimal getOthOutAmt() {
        return othOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.OTH_OUT_AMT
     *
     * @param othOutAmt the value for HMFS.HM_ACTINFO_CBS.OTH_OUT_AMT
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setOthOutAmt(BigDecimal othOutAmt) {
        this.othOutAmt = othOutAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.REMARK
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.REMARK
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.REMARK
     *
     * @param remark the value for HMFS.HM_ACTINFO_CBS.REMARK
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_ACTINFO_CBS.RECVERSION
     *
     * @return the value of HMFS.HM_ACTINFO_CBS.RECVERSION
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_ACTINFO_CBS.RECVERSION
     *
     * @param recversion the value for HMFS.HM_ACTINFO_CBS.RECVERSION
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }
}