package common.repository.hmfs.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class HmChkActExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public HmChkActExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIsNull() {
            addCriterion("SEND_SYS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIsNotNull() {
            addCriterion("SEND_SYS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSendSysIdEqualTo(String value) {
            addCriterion("SEND_SYS_ID =", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotEqualTo(String value) {
            addCriterion("SEND_SYS_ID <>", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdGreaterThan(String value) {
            addCriterion("SEND_SYS_ID >", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_SYS_ID >=", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLessThan(String value) {
            addCriterion("SEND_SYS_ID <", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLessThanOrEqualTo(String value) {
            addCriterion("SEND_SYS_ID <=", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdLike(String value) {
            addCriterion("SEND_SYS_ID like", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotLike(String value) {
            addCriterion("SEND_SYS_ID not like", value, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdIn(List<String> values) {
            addCriterion("SEND_SYS_ID in", values, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotIn(List<String> values) {
            addCriterion("SEND_SYS_ID not in", values, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdBetween(String value1, String value2) {
            addCriterion("SEND_SYS_ID between", value1, value2, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andSendSysIdNotBetween(String value1, String value2) {
            addCriterion("SEND_SYS_ID not between", value1, value2, "sendSysId");
            return (Criteria) this;
        }

        public Criteria andActnoIsNull() {
            addCriterion("ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andActnoIsNotNull() {
            addCriterion("ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andActnoEqualTo(String value) {
            addCriterion("ACTNO =", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotEqualTo(String value) {
            addCriterion("ACTNO <>", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThan(String value) {
            addCriterion("ACTNO >", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACTNO >=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThan(String value) {
            addCriterion("ACTNO <", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThanOrEqualTo(String value) {
            addCriterion("ACTNO <=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLike(String value) {
            addCriterion("ACTNO like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotLike(String value) {
            addCriterion("ACTNO not like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoIn(List<String> values) {
            addCriterion("ACTNO in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotIn(List<String> values) {
            addCriterion("ACTNO not in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoBetween(String value1, String value2) {
            addCriterion("ACTNO between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotBetween(String value1, String value2) {
            addCriterion("ACTNO not between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andActbalIsNull() {
            addCriterion("ACTBAL is null");
            return (Criteria) this;
        }

        public Criteria andActbalIsNotNull() {
            addCriterion("ACTBAL is not null");
            return (Criteria) this;
        }

        public Criteria andActbalEqualTo(BigDecimal value) {
            addCriterion("ACTBAL =", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalNotEqualTo(BigDecimal value) {
            addCriterion("ACTBAL <>", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalGreaterThan(BigDecimal value) {
            addCriterion("ACTBAL >", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTBAL >=", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalLessThan(BigDecimal value) {
            addCriterion("ACTBAL <", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ACTBAL <=", value, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalIn(List<BigDecimal> values) {
            addCriterion("ACTBAL in", values, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalNotIn(List<BigDecimal> values) {
            addCriterion("ACTBAL not in", values, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTBAL between", value1, value2, "actbal");
            return (Criteria) this;
        }

        public Criteria andActbalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ACTBAL not between", value1, value2, "actbal");
            return (Criteria) this;
        }

        public Criteria andChkstsIsNull() {
            addCriterion("CHKSTS is null");
            return (Criteria) this;
        }

        public Criteria andChkstsIsNotNull() {
            addCriterion("CHKSTS is not null");
            return (Criteria) this;
        }

        public Criteria andChkstsEqualTo(String value) {
            addCriterion("CHKSTS =", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotEqualTo(String value) {
            addCriterion("CHKSTS <>", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsGreaterThan(String value) {
            addCriterion("CHKSTS >", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsGreaterThanOrEqualTo(String value) {
            addCriterion("CHKSTS >=", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLessThan(String value) {
            addCriterion("CHKSTS <", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLessThanOrEqualTo(String value) {
            addCriterion("CHKSTS <=", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsLike(String value) {
            addCriterion("CHKSTS like", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotLike(String value) {
            addCriterion("CHKSTS not like", value, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsIn(List<String> values) {
            addCriterion("CHKSTS in", values, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotIn(List<String> values) {
            addCriterion("CHKSTS not in", values, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsBetween(String value1, String value2) {
            addCriterion("CHKSTS between", value1, value2, "chksts");
            return (Criteria) this;
        }

        public Criteria andChkstsNotBetween(String value1, String value2) {
            addCriterion("CHKSTS not between", value1, value2, "chksts");
            return (Criteria) this;
        }

        public Criteria andInfoId1IsNull() {
            addCriterion("INFO_ID1 is null");
            return (Criteria) this;
        }

        public Criteria andInfoId1IsNotNull() {
            addCriterion("INFO_ID1 is not null");
            return (Criteria) this;
        }

        public Criteria andInfoId1EqualTo(String value) {
            addCriterion("INFO_ID1 =", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1NotEqualTo(String value) {
            addCriterion("INFO_ID1 <>", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1GreaterThan(String value) {
            addCriterion("INFO_ID1 >", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1GreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID1 >=", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1LessThan(String value) {
            addCriterion("INFO_ID1 <", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1LessThanOrEqualTo(String value) {
            addCriterion("INFO_ID1 <=", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1Like(String value) {
            addCriterion("INFO_ID1 like", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1NotLike(String value) {
            addCriterion("INFO_ID1 not like", value, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1In(List<String> values) {
            addCriterion("INFO_ID1 in", values, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1NotIn(List<String> values) {
            addCriterion("INFO_ID1 not in", values, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1Between(String value1, String value2) {
            addCriterion("INFO_ID1 between", value1, value2, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoId1NotBetween(String value1, String value2) {
            addCriterion("INFO_ID1 not between", value1, value2, "infoId1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1IsNull() {
            addCriterion("INFO_ID_TYPE1 is null");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1IsNotNull() {
            addCriterion("INFO_ID_TYPE1 is not null");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1EqualTo(String value) {
            addCriterion("INFO_ID_TYPE1 =", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1NotEqualTo(String value) {
            addCriterion("INFO_ID_TYPE1 <>", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1GreaterThan(String value) {
            addCriterion("INFO_ID_TYPE1 >", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1GreaterThanOrEqualTo(String value) {
            addCriterion("INFO_ID_TYPE1 >=", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1LessThan(String value) {
            addCriterion("INFO_ID_TYPE1 <", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1LessThanOrEqualTo(String value) {
            addCriterion("INFO_ID_TYPE1 <=", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1Like(String value) {
            addCriterion("INFO_ID_TYPE1 like", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1NotLike(String value) {
            addCriterion("INFO_ID_TYPE1 not like", value, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1In(List<String> values) {
            addCriterion("INFO_ID_TYPE1 in", values, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1NotIn(List<String> values) {
            addCriterion("INFO_ID_TYPE1 not in", values, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1Between(String value1, String value2) {
            addCriterion("INFO_ID_TYPE1 between", value1, value2, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andInfoIdType1NotBetween(String value1, String value2) {
            addCriterion("INFO_ID_TYPE1 not between", value1, value2, "infoIdType1");
            return (Criteria) this;
        }

        public Criteria andCellNumIsNull() {
            addCriterion("CELL_NUM is null");
            return (Criteria) this;
        }

        public Criteria andCellNumIsNotNull() {
            addCriterion("CELL_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andCellNumEqualTo(String value) {
            addCriterion("CELL_NUM =", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumNotEqualTo(String value) {
            addCriterion("CELL_NUM <>", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumGreaterThan(String value) {
            addCriterion("CELL_NUM >", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumGreaterThanOrEqualTo(String value) {
            addCriterion("CELL_NUM >=", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumLessThan(String value) {
            addCriterion("CELL_NUM <", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumLessThanOrEqualTo(String value) {
            addCriterion("CELL_NUM <=", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumLike(String value) {
            addCriterion("CELL_NUM like", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumNotLike(String value) {
            addCriterion("CELL_NUM not like", value, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumIn(List<String> values) {
            addCriterion("CELL_NUM in", values, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumNotIn(List<String> values) {
            addCriterion("CELL_NUM not in", values, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumBetween(String value1, String value2) {
            addCriterion("CELL_NUM between", value1, value2, "cellNum");
            return (Criteria) this;
        }

        public Criteria andCellNumNotBetween(String value1, String value2) {
            addCriterion("CELL_NUM not between", value1, value2, "cellNum");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaIsNull() {
            addCriterion("BUILDER_AREA is null");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaIsNotNull() {
            addCriterion("BUILDER_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaEqualTo(String value) {
            addCriterion("BUILDER_AREA =", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaNotEqualTo(String value) {
            addCriterion("BUILDER_AREA <>", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaGreaterThan(String value) {
            addCriterion("BUILDER_AREA >", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaGreaterThanOrEqualTo(String value) {
            addCriterion("BUILDER_AREA >=", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaLessThan(String value) {
            addCriterion("BUILDER_AREA <", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaLessThanOrEqualTo(String value) {
            addCriterion("BUILDER_AREA <=", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaLike(String value) {
            addCriterion("BUILDER_AREA like", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaNotLike(String value) {
            addCriterion("BUILDER_AREA not like", value, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaIn(List<String> values) {
            addCriterion("BUILDER_AREA in", values, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaNotIn(List<String> values) {
            addCriterion("BUILDER_AREA not in", values, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaBetween(String value1, String value2) {
            addCriterion("BUILDER_AREA between", value1, value2, "builderArea");
            return (Criteria) this;
        }

        public Criteria andBuilderAreaNotBetween(String value1, String value2) {
            addCriterion("BUILDER_AREA not between", value1, value2, "builderArea");
            return (Criteria) this;
        }

        public Criteria andActtypeIsNull() {
            addCriterion("ACTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andActtypeIsNotNull() {
            addCriterion("ACTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andActtypeEqualTo(String value) {
            addCriterion("ACTTYPE =", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotEqualTo(String value) {
            addCriterion("ACTTYPE <>", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeGreaterThan(String value) {
            addCriterion("ACTTYPE >", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeGreaterThanOrEqualTo(String value) {
            addCriterion("ACTTYPE >=", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeLessThan(String value) {
            addCriterion("ACTTYPE <", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeLessThanOrEqualTo(String value) {
            addCriterion("ACTTYPE <=", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeLike(String value) {
            addCriterion("ACTTYPE like", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotLike(String value) {
            addCriterion("ACTTYPE not like", value, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeIn(List<String> values) {
            addCriterion("ACTTYPE in", values, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotIn(List<String> values) {
            addCriterion("ACTTYPE not in", values, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeBetween(String value1, String value2) {
            addCriterion("ACTTYPE between", value1, value2, "acttype");
            return (Criteria) this;
        }

        public Criteria andActtypeNotBetween(String value1, String value2) {
            addCriterion("ACTTYPE not between", value1, value2, "acttype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 10 17:21:41 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}