package common.repository.hmfs.model;

import java.math.BigDecimal;

public class HmChkAct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String sendSysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String actno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private BigDecimal actbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String chksts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.INFO_ID1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String infoId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.INFO_ID_TYPE1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String infoIdType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.CELL_NUM
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String cellNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.BUILDER_AREA
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String builderArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.ACTTYPE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    private String acttype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.PKID
     *
     * @return the value of HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.PKID
     *
     * @param pkid the value for HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @return the value of HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @param txnDate the value for HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @return the value of HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getSendSysId() {
        return sendSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @param sendSysId the value for HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setSendSysId(String sendSysId) {
        this.sendSysId = sendSysId == null ? null : sendSysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @return the value of HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getActno() {
        return actno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @param actno the value for HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setActno(String actno) {
        this.actno = actno == null ? null : actno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @return the value of HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public BigDecimal getActbal() {
        return actbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @param actbal the value for HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setActbal(BigDecimal actbal) {
        this.actbal = actbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @return the value of HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getChksts() {
        return chksts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @param chksts the value for HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setChksts(String chksts) {
        this.chksts = chksts == null ? null : chksts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.INFO_ID1
     *
     * @return the value of HMFS.HM_CHK_ACT.INFO_ID1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getInfoId1() {
        return infoId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.INFO_ID1
     *
     * @param infoId1 the value for HMFS.HM_CHK_ACT.INFO_ID1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setInfoId1(String infoId1) {
        this.infoId1 = infoId1 == null ? null : infoId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.INFO_ID_TYPE1
     *
     * @return the value of HMFS.HM_CHK_ACT.INFO_ID_TYPE1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getInfoIdType1() {
        return infoIdType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.INFO_ID_TYPE1
     *
     * @param infoIdType1 the value for HMFS.HM_CHK_ACT.INFO_ID_TYPE1
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setInfoIdType1(String infoIdType1) {
        this.infoIdType1 = infoIdType1 == null ? null : infoIdType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.CELL_NUM
     *
     * @return the value of HMFS.HM_CHK_ACT.CELL_NUM
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getCellNum() {
        return cellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.CELL_NUM
     *
     * @param cellNum the value for HMFS.HM_CHK_ACT.CELL_NUM
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setCellNum(String cellNum) {
        this.cellNum = cellNum == null ? null : cellNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.BUILDER_AREA
     *
     * @return the value of HMFS.HM_CHK_ACT.BUILDER_AREA
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getBuilderArea() {
        return builderArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.BUILDER_AREA
     *
     * @param builderArea the value for HMFS.HM_CHK_ACT.BUILDER_AREA
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setBuilderArea(String builderArea) {
        this.builderArea = builderArea == null ? null : builderArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.ACTTYPE
     *
     * @return the value of HMFS.HM_CHK_ACT.ACTTYPE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public String getActtype() {
        return acttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.ACTTYPE
     *
     * @param acttype the value for HMFS.HM_CHK_ACT.ACTTYPE
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    public void setActtype(String acttype) {
        this.acttype = acttype == null ? null : acttype.trim();
    }
}