package common.repository.hmfs.model;

public class HmSct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.SCT_SEQNO
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String sctSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.BANK_ID
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.BANK_NAME
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.SYS_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String sysSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.CBS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String cbsChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.FCS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String fcsChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.LAST_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String lastIntDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.NEXT_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private String nextIntDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SCT.TXNSEQ
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    private Integer txnseq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.SCT_SEQNO
     *
     * @return the value of HMFS.HM_SCT.SCT_SEQNO
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getSctSeqno() {
        return sctSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.SCT_SEQNO
     *
     * @param sctSeqno the value for HMFS.HM_SCT.SCT_SEQNO
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setSctSeqno(String sctSeqno) {
        this.sctSeqno = sctSeqno == null ? null : sctSeqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.BANK_ID
     *
     * @return the value of HMFS.HM_SCT.BANK_ID
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.BANK_ID
     *
     * @param bankId the value for HMFS.HM_SCT.BANK_ID
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.BANK_NAME
     *
     * @return the value of HMFS.HM_SCT.BANK_NAME
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.BANK_NAME
     *
     * @param bankName the value for HMFS.HM_SCT.BANK_NAME
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.SYS_STS
     *
     * @return the value of HMFS.HM_SCT.SYS_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getSysSts() {
        return sysSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.SYS_STS
     *
     * @param sysSts the value for HMFS.HM_SCT.SYS_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setSysSts(String sysSts) {
        this.sysSts = sysSts == null ? null : sysSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.TXN_DATE
     *
     * @return the value of HMFS.HM_SCT.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.TXN_DATE
     *
     * @param txnDate the value for HMFS.HM_SCT.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.CBS_CHK_STS
     *
     * @return the value of HMFS.HM_SCT.CBS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getCbsChkSts() {
        return cbsChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.CBS_CHK_STS
     *
     * @param cbsChkSts the value for HMFS.HM_SCT.CBS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setCbsChkSts(String cbsChkSts) {
        this.cbsChkSts = cbsChkSts == null ? null : cbsChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.FCS_CHK_STS
     *
     * @return the value of HMFS.HM_SCT.FCS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getFcsChkSts() {
        return fcsChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.FCS_CHK_STS
     *
     * @param fcsChkSts the value for HMFS.HM_SCT.FCS_CHK_STS
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setFcsChkSts(String fcsChkSts) {
        this.fcsChkSts = fcsChkSts == null ? null : fcsChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.LAST_INT_DATE
     *
     * @return the value of HMFS.HM_SCT.LAST_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getLastIntDate() {
        return lastIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.LAST_INT_DATE
     *
     * @param lastIntDate the value for HMFS.HM_SCT.LAST_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setLastIntDate(String lastIntDate) {
        this.lastIntDate = lastIntDate == null ? null : lastIntDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.NEXT_INT_DATE
     *
     * @return the value of HMFS.HM_SCT.NEXT_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public String getNextIntDate() {
        return nextIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.NEXT_INT_DATE
     *
     * @param nextIntDate the value for HMFS.HM_SCT.NEXT_INT_DATE
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setNextIntDate(String nextIntDate) {
        this.nextIntDate = nextIntDate == null ? null : nextIntDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SCT.TXNSEQ
     *
     * @return the value of HMFS.HM_SCT.TXNSEQ
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public Integer getTxnseq() {
        return txnseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SCT.TXNSEQ
     *
     * @param txnseq the value for HMFS.HM_SCT.TXNSEQ
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    public void setTxnseq(Integer txnseq) {
        this.txnseq = txnseq;
    }
}