package common.repository.hmfs.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HmSysCtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public HmSysCtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSctSeqnoIsNull() {
            addCriterion("SCT_SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoIsNotNull() {
            addCriterion("SCT_SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoEqualTo(String value) {
            addCriterion("SCT_SEQNO =", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoNotEqualTo(String value) {
            addCriterion("SCT_SEQNO <>", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoGreaterThan(String value) {
            addCriterion("SCT_SEQNO >", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoGreaterThanOrEqualTo(String value) {
            addCriterion("SCT_SEQNO >=", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoLessThan(String value) {
            addCriterion("SCT_SEQNO <", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoLessThanOrEqualTo(String value) {
            addCriterion("SCT_SEQNO <=", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoLike(String value) {
            addCriterion("SCT_SEQNO like", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoNotLike(String value) {
            addCriterion("SCT_SEQNO not like", value, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoIn(List<String> values) {
            addCriterion("SCT_SEQNO in", values, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoNotIn(List<String> values) {
            addCriterion("SCT_SEQNO not in", values, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoBetween(String value1, String value2) {
            addCriterion("SCT_SEQNO between", value1, value2, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andSctSeqnoNotBetween(String value1, String value2) {
            addCriterion("SCT_SEQNO not between", value1, value2, "sctSeqno");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BANK_ID like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BANK_ID not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andSysStsIsNull() {
            addCriterion("SYS_STS is null");
            return (Criteria) this;
        }

        public Criteria andSysStsIsNotNull() {
            addCriterion("SYS_STS is not null");
            return (Criteria) this;
        }

        public Criteria andSysStsEqualTo(String value) {
            addCriterion("SYS_STS =", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsNotEqualTo(String value) {
            addCriterion("SYS_STS <>", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsGreaterThan(String value) {
            addCriterion("SYS_STS >", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_STS >=", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsLessThan(String value) {
            addCriterion("SYS_STS <", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsLessThanOrEqualTo(String value) {
            addCriterion("SYS_STS <=", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsLike(String value) {
            addCriterion("SYS_STS like", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsNotLike(String value) {
            addCriterion("SYS_STS not like", value, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsIn(List<String> values) {
            addCriterion("SYS_STS in", values, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsNotIn(List<String> values) {
            addCriterion("SYS_STS not in", values, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsBetween(String value1, String value2) {
            addCriterion("SYS_STS between", value1, value2, "sysSts");
            return (Criteria) this;
        }

        public Criteria andSysStsNotBetween(String value1, String value2) {
            addCriterion("SYS_STS not between", value1, value2, "sysSts");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsIsNull() {
            addCriterion("CBS_CHK_STS is null");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsIsNotNull() {
            addCriterion("CBS_CHK_STS is not null");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsEqualTo(String value) {
            addCriterion("CBS_CHK_STS =", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsNotEqualTo(String value) {
            addCriterion("CBS_CHK_STS <>", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsGreaterThan(String value) {
            addCriterion("CBS_CHK_STS >", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsGreaterThanOrEqualTo(String value) {
            addCriterion("CBS_CHK_STS >=", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsLessThan(String value) {
            addCriterion("CBS_CHK_STS <", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsLessThanOrEqualTo(String value) {
            addCriterion("CBS_CHK_STS <=", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsLike(String value) {
            addCriterion("CBS_CHK_STS like", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsNotLike(String value) {
            addCriterion("CBS_CHK_STS not like", value, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsIn(List<String> values) {
            addCriterion("CBS_CHK_STS in", values, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsNotIn(List<String> values) {
            addCriterion("CBS_CHK_STS not in", values, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsBetween(String value1, String value2) {
            addCriterion("CBS_CHK_STS between", value1, value2, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andCbsChkStsNotBetween(String value1, String value2) {
            addCriterion("CBS_CHK_STS not between", value1, value2, "cbsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsIsNull() {
            addCriterion("FCS_CHK_STS is null");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsIsNotNull() {
            addCriterion("FCS_CHK_STS is not null");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsEqualTo(String value) {
            addCriterion("FCS_CHK_STS =", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsNotEqualTo(String value) {
            addCriterion("FCS_CHK_STS <>", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsGreaterThan(String value) {
            addCriterion("FCS_CHK_STS >", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsGreaterThanOrEqualTo(String value) {
            addCriterion("FCS_CHK_STS >=", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsLessThan(String value) {
            addCriterion("FCS_CHK_STS <", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsLessThanOrEqualTo(String value) {
            addCriterion("FCS_CHK_STS <=", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsLike(String value) {
            addCriterion("FCS_CHK_STS like", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsNotLike(String value) {
            addCriterion("FCS_CHK_STS not like", value, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsIn(List<String> values) {
            addCriterion("FCS_CHK_STS in", values, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsNotIn(List<String> values) {
            addCriterion("FCS_CHK_STS not in", values, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsBetween(String value1, String value2) {
            addCriterion("FCS_CHK_STS between", value1, value2, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andFcsChkStsNotBetween(String value1, String value2) {
            addCriterion("FCS_CHK_STS not between", value1, value2, "fcsChkSts");
            return (Criteria) this;
        }

        public Criteria andLastIntDateIsNull() {
            addCriterion("LAST_INT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastIntDateIsNotNull() {
            addCriterion("LAST_INT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastIntDateEqualTo(String value) {
            addCriterion("LAST_INT_DATE =", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateNotEqualTo(String value) {
            addCriterion("LAST_INT_DATE <>", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateGreaterThan(String value) {
            addCriterion("LAST_INT_DATE >", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_INT_DATE >=", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateLessThan(String value) {
            addCriterion("LAST_INT_DATE <", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateLessThanOrEqualTo(String value) {
            addCriterion("LAST_INT_DATE <=", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateLike(String value) {
            addCriterion("LAST_INT_DATE like", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateNotLike(String value) {
            addCriterion("LAST_INT_DATE not like", value, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateIn(List<String> values) {
            addCriterion("LAST_INT_DATE in", values, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateNotIn(List<String> values) {
            addCriterion("LAST_INT_DATE not in", values, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateBetween(String value1, String value2) {
            addCriterion("LAST_INT_DATE between", value1, value2, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andLastIntDateNotBetween(String value1, String value2) {
            addCriterion("LAST_INT_DATE not between", value1, value2, "lastIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateIsNull() {
            addCriterion("NEXT_INT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andNextIntDateIsNotNull() {
            addCriterion("NEXT_INT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andNextIntDateEqualTo(String value) {
            addCriterion("NEXT_INT_DATE =", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateNotEqualTo(String value) {
            addCriterion("NEXT_INT_DATE <>", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateGreaterThan(String value) {
            addCriterion("NEXT_INT_DATE >", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateGreaterThanOrEqualTo(String value) {
            addCriterion("NEXT_INT_DATE >=", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateLessThan(String value) {
            addCriterion("NEXT_INT_DATE <", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateLessThanOrEqualTo(String value) {
            addCriterion("NEXT_INT_DATE <=", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateLike(String value) {
            addCriterion("NEXT_INT_DATE like", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateNotLike(String value) {
            addCriterion("NEXT_INT_DATE not like", value, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateIn(List<String> values) {
            addCriterion("NEXT_INT_DATE in", values, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateNotIn(List<String> values) {
            addCriterion("NEXT_INT_DATE not in", values, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateBetween(String value1, String value2) {
            addCriterion("NEXT_INT_DATE between", value1, value2, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andNextIntDateNotBetween(String value1, String value2) {
            addCriterion("NEXT_INT_DATE not between", value1, value2, "nextIntDate");
            return (Criteria) this;
        }

        public Criteria andTxnseqIsNull() {
            addCriterion("TXNSEQ is null");
            return (Criteria) this;
        }

        public Criteria andTxnseqIsNotNull() {
            addCriterion("TXNSEQ is not null");
            return (Criteria) this;
        }

        public Criteria andTxnseqEqualTo(Integer value) {
            addCriterion("TXNSEQ =", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqNotEqualTo(Integer value) {
            addCriterion("TXNSEQ <>", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqGreaterThan(Integer value) {
            addCriterion("TXNSEQ >", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqGreaterThanOrEqualTo(Integer value) {
            addCriterion("TXNSEQ >=", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqLessThan(Integer value) {
            addCriterion("TXNSEQ <", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqLessThanOrEqualTo(Integer value) {
            addCriterion("TXNSEQ <=", value, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqIn(List<Integer> values) {
            addCriterion("TXNSEQ in", values, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqNotIn(List<Integer> values) {
            addCriterion("TXNSEQ not in", values, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqBetween(Integer value1, Integer value2) {
            addCriterion("TXNSEQ between", value1, value2, "txnseq");
            return (Criteria) this;
        }

        public Criteria andTxnseqNotBetween(Integer value1, Integer value2) {
            addCriterion("TXNSEQ not between", value1, value2, "txnseq");
            return (Criteria) this;
        }

        public Criteria andSignonDtIsNull() {
            addCriterion("SIGNON_DT is null");
            return (Criteria) this;
        }

        public Criteria andSignonDtIsNotNull() {
            addCriterion("SIGNON_DT is not null");
            return (Criteria) this;
        }

        public Criteria andSignonDtEqualTo(Date value) {
            addCriterion("SIGNON_DT =", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtNotEqualTo(Date value) {
            addCriterion("SIGNON_DT <>", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtGreaterThan(Date value) {
            addCriterion("SIGNON_DT >", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtGreaterThanOrEqualTo(Date value) {
            addCriterion("SIGNON_DT >=", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtLessThan(Date value) {
            addCriterion("SIGNON_DT <", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtLessThanOrEqualTo(Date value) {
            addCriterion("SIGNON_DT <=", value, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtIn(List<Date> values) {
            addCriterion("SIGNON_DT in", values, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtNotIn(List<Date> values) {
            addCriterion("SIGNON_DT not in", values, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtBetween(Date value1, Date value2) {
            addCriterion("SIGNON_DT between", value1, value2, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignonDtNotBetween(Date value1, Date value2) {
            addCriterion("SIGNON_DT not between", value1, value2, "signonDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtIsNull() {
            addCriterion("SIGNOUT_DT is null");
            return (Criteria) this;
        }

        public Criteria andSignoutDtIsNotNull() {
            addCriterion("SIGNOUT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andSignoutDtEqualTo(Date value) {
            addCriterion("SIGNOUT_DT =", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtNotEqualTo(Date value) {
            addCriterion("SIGNOUT_DT <>", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtGreaterThan(Date value) {
            addCriterion("SIGNOUT_DT >", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtGreaterThanOrEqualTo(Date value) {
            addCriterion("SIGNOUT_DT >=", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtLessThan(Date value) {
            addCriterion("SIGNOUT_DT <", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtLessThanOrEqualTo(Date value) {
            addCriterion("SIGNOUT_DT <=", value, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtIn(List<Date> values) {
            addCriterion("SIGNOUT_DT in", values, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtNotIn(List<Date> values) {
            addCriterion("SIGNOUT_DT not in", values, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtBetween(Date value1, Date value2) {
            addCriterion("SIGNOUT_DT between", value1, value2, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andSignoutDtNotBetween(Date value1, Date value2) {
            addCriterion("SIGNOUT_DT not between", value1, value2, "signoutDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIsNull() {
            addCriterion("HOST_CHK_DT is null");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIsNotNull() {
            addCriterion("HOST_CHK_DT is not null");
            return (Criteria) this;
        }

        public Criteria andHostChkDtEqualTo(Date value) {
            addCriterion("HOST_CHK_DT =", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotEqualTo(Date value) {
            addCriterion("HOST_CHK_DT <>", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtGreaterThan(Date value) {
            addCriterion("HOST_CHK_DT >", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtGreaterThanOrEqualTo(Date value) {
            addCriterion("HOST_CHK_DT >=", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtLessThan(Date value) {
            addCriterion("HOST_CHK_DT <", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtLessThanOrEqualTo(Date value) {
            addCriterion("HOST_CHK_DT <=", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIn(List<Date> values) {
            addCriterion("HOST_CHK_DT in", values, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotIn(List<Date> values) {
            addCriterion("HOST_CHK_DT not in", values, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtBetween(Date value1, Date value2) {
            addCriterion("HOST_CHK_DT between", value1, value2, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotBetween(Date value1, Date value2) {
            addCriterion("HOST_CHK_DT not between", value1, value2, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtIsNull() {
            addCriterion("HMB_CHK_DT is null");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtIsNotNull() {
            addCriterion("HMB_CHK_DT is not null");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtEqualTo(Date value) {
            addCriterion("HMB_CHK_DT =", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtNotEqualTo(Date value) {
            addCriterion("HMB_CHK_DT <>", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtGreaterThan(Date value) {
            addCriterion("HMB_CHK_DT >", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtGreaterThanOrEqualTo(Date value) {
            addCriterion("HMB_CHK_DT >=", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtLessThan(Date value) {
            addCriterion("HMB_CHK_DT <", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtLessThanOrEqualTo(Date value) {
            addCriterion("HMB_CHK_DT <=", value, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtIn(List<Date> values) {
            addCriterion("HMB_CHK_DT in", values, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtNotIn(List<Date> values) {
            addCriterion("HMB_CHK_DT not in", values, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtBetween(Date value1, Date value2) {
            addCriterion("HMB_CHK_DT between", value1, value2, "hmbChkDt");
            return (Criteria) this;
        }

        public Criteria andHmbChkDtNotBetween(Date value1, Date value2) {
            addCriterion("HMB_CHK_DT not between", value1, value2, "hmbChkDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 12 23:16:28 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 23:16:28 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}