package common.repository.hmfs.model;

import java.util.Date;

public class HmSysCtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String sctSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.BANK_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.SYS_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String sysSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String cbsChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.FCS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String fcsChkSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.LAST_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String lastIntDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.NEXT_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String nextIntDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.TXNSEQ
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private Integer txnseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.SIGNON_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private Date signonDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.SIGNOUT_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private Date signoutDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private Date hostChkDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_SYS_CTL.HMB_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private Date hmbChkDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.SCT_SEQNO
     *
     * @return the value of HMFS.HM_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getSctSeqno() {
        return sctSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.SCT_SEQNO
     *
     * @param sctSeqno the value for HMFS.HM_SYS_CTL.SCT_SEQNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setSctSeqno(String sctSeqno) {
        this.sctSeqno = sctSeqno == null ? null : sctSeqno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.BANK_ID
     *
     * @return the value of HMFS.HM_SYS_CTL.BANK_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.BANK_ID
     *
     * @param bankId the value for HMFS.HM_SYS_CTL.BANK_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.BANK_NAME
     *
     * @return the value of HMFS.HM_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.BANK_NAME
     *
     * @param bankName the value for HMFS.HM_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.SYS_STS
     *
     * @return the value of HMFS.HM_SYS_CTL.SYS_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getSysSts() {
        return sysSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.SYS_STS
     *
     * @param sysSts the value for HMFS.HM_SYS_CTL.SYS_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setSysSts(String sysSts) {
        this.sysSts = sysSts == null ? null : sysSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.TXN_DATE
     *
     * @return the value of HMFS.HM_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.TXN_DATE
     *
     * @param txnDate the value for HMFS.HM_SYS_CTL.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.CBS_CHK_STS
     *
     * @return the value of HMFS.HM_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getCbsChkSts() {
        return cbsChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.CBS_CHK_STS
     *
     * @param cbsChkSts the value for HMFS.HM_SYS_CTL.CBS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setCbsChkSts(String cbsChkSts) {
        this.cbsChkSts = cbsChkSts == null ? null : cbsChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.FCS_CHK_STS
     *
     * @return the value of HMFS.HM_SYS_CTL.FCS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getFcsChkSts() {
        return fcsChkSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.FCS_CHK_STS
     *
     * @param fcsChkSts the value for HMFS.HM_SYS_CTL.FCS_CHK_STS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setFcsChkSts(String fcsChkSts) {
        this.fcsChkSts = fcsChkSts == null ? null : fcsChkSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.LAST_INT_DATE
     *
     * @return the value of HMFS.HM_SYS_CTL.LAST_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getLastIntDate() {
        return lastIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.LAST_INT_DATE
     *
     * @param lastIntDate the value for HMFS.HM_SYS_CTL.LAST_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setLastIntDate(String lastIntDate) {
        this.lastIntDate = lastIntDate == null ? null : lastIntDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.NEXT_INT_DATE
     *
     * @return the value of HMFS.HM_SYS_CTL.NEXT_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getNextIntDate() {
        return nextIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.NEXT_INT_DATE
     *
     * @param nextIntDate the value for HMFS.HM_SYS_CTL.NEXT_INT_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setNextIntDate(String nextIntDate) {
        this.nextIntDate = nextIntDate == null ? null : nextIntDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.TXNSEQ
     *
     * @return the value of HMFS.HM_SYS_CTL.TXNSEQ
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public Integer getTxnseq() {
        return txnseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.TXNSEQ
     *
     * @param txnseq the value for HMFS.HM_SYS_CTL.TXNSEQ
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setTxnseq(Integer txnseq) {
        this.txnseq = txnseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.SIGNON_DT
     *
     * @return the value of HMFS.HM_SYS_CTL.SIGNON_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public Date getSignonDt() {
        return signonDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.SIGNON_DT
     *
     * @param signonDt the value for HMFS.HM_SYS_CTL.SIGNON_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setSignonDt(Date signonDt) {
        this.signonDt = signonDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.SIGNOUT_DT
     *
     * @return the value of HMFS.HM_SYS_CTL.SIGNOUT_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public Date getSignoutDt() {
        return signoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.SIGNOUT_DT
     *
     * @param signoutDt the value for HMFS.HM_SYS_CTL.SIGNOUT_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setSignoutDt(Date signoutDt) {
        this.signoutDt = signoutDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.HOST_CHK_DT
     *
     * @return the value of HMFS.HM_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public Date getHostChkDt() {
        return hostChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.HOST_CHK_DT
     *
     * @param hostChkDt the value for HMFS.HM_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setHostChkDt(Date hostChkDt) {
        this.hostChkDt = hostChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_SYS_CTL.HMB_CHK_DT
     *
     * @return the value of HMFS.HM_SYS_CTL.HMB_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public Date getHmbChkDt() {
        return hmbChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_SYS_CTL.HMB_CHK_DT
     *
     * @param hmbChkDt the value for HMFS.HM_SYS_CTL.HMB_CHK_DT
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setHmbChkDt(Date hmbChkDt) {
        this.hmbChkDt = hmbChkDt;
    }
}