package common.repository.hmfs.model;

public class HmVchJrnl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.PKID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.VCH_COUNT
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private Long vchCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.VCH_START_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String vchStartNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.VCH_END_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String vchEndNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.VCH_STATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String vchState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.BRANCH_ID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.OPR_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String oprNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.OPR_DATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String oprDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.REMARK
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_VCH_JRNL.RECVERSION
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    private Integer recversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.PKID
     *
     * @return the value of HMFS.HM_VCH_JRNL.PKID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.PKID
     *
     * @param pkid the value for HMFS.HM_VCH_JRNL.PKID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.VCH_COUNT
     *
     * @return the value of HMFS.HM_VCH_JRNL.VCH_COUNT
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public Long getVchCount() {
        return vchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.VCH_COUNT
     *
     * @param vchCount the value for HMFS.HM_VCH_JRNL.VCH_COUNT
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setVchCount(Long vchCount) {
        this.vchCount = vchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.VCH_START_NO
     *
     * @return the value of HMFS.HM_VCH_JRNL.VCH_START_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getVchStartNo() {
        return vchStartNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.VCH_START_NO
     *
     * @param vchStartNo the value for HMFS.HM_VCH_JRNL.VCH_START_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setVchStartNo(String vchStartNo) {
        this.vchStartNo = vchStartNo == null ? null : vchStartNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.VCH_END_NO
     *
     * @return the value of HMFS.HM_VCH_JRNL.VCH_END_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getVchEndNo() {
        return vchEndNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.VCH_END_NO
     *
     * @param vchEndNo the value for HMFS.HM_VCH_JRNL.VCH_END_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setVchEndNo(String vchEndNo) {
        this.vchEndNo = vchEndNo == null ? null : vchEndNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.VCH_STATE
     *
     * @return the value of HMFS.HM_VCH_JRNL.VCH_STATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getVchState() {
        return vchState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.VCH_STATE
     *
     * @param vchState the value for HMFS.HM_VCH_JRNL.VCH_STATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setVchState(String vchState) {
        this.vchState = vchState == null ? null : vchState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.BRANCH_ID
     *
     * @return the value of HMFS.HM_VCH_JRNL.BRANCH_ID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.BRANCH_ID
     *
     * @param branchId the value for HMFS.HM_VCH_JRNL.BRANCH_ID
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.OPR_NO
     *
     * @return the value of HMFS.HM_VCH_JRNL.OPR_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getOprNo() {
        return oprNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.OPR_NO
     *
     * @param oprNo the value for HMFS.HM_VCH_JRNL.OPR_NO
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setOprNo(String oprNo) {
        this.oprNo = oprNo == null ? null : oprNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.OPR_DATE
     *
     * @return the value of HMFS.HM_VCH_JRNL.OPR_DATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getOprDate() {
        return oprDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.OPR_DATE
     *
     * @param oprDate the value for HMFS.HM_VCH_JRNL.OPR_DATE
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setOprDate(String oprDate) {
        this.oprDate = oprDate == null ? null : oprDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.REMARK
     *
     * @return the value of HMFS.HM_VCH_JRNL.REMARK
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.REMARK
     *
     * @param remark the value for HMFS.HM_VCH_JRNL.REMARK
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_VCH_JRNL.RECVERSION
     *
     * @return the value of HMFS.HM_VCH_JRNL.RECVERSION
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_VCH_JRNL.RECVERSION
     *
     * @param recversion the value for HMFS.HM_VCH_JRNL.RECVERSION
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }
}