package common.repository.hmfs.model;

import java.util.ArrayList;
import java.util.List;

public class TxnVouchLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public TxnVouchLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andTxnSnIsNull() {
            addCriterion("TXN_SN is null");
            return (Criteria) this;
        }

        public Criteria andTxnSnIsNotNull() {
            addCriterion("TXN_SN is not null");
            return (Criteria) this;
        }

        public Criteria andTxnSnEqualTo(String value) {
            addCriterion("TXN_SN =", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotEqualTo(String value) {
            addCriterion("TXN_SN <>", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnGreaterThan(String value) {
            addCriterion("TXN_SN >", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_SN >=", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLessThan(String value) {
            addCriterion("TXN_SN <", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLessThanOrEqualTo(String value) {
            addCriterion("TXN_SN <=", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnLike(String value) {
            addCriterion("TXN_SN like", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotLike(String value) {
            addCriterion("TXN_SN not like", value, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnIn(List<String> values) {
            addCriterion("TXN_SN in", values, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotIn(List<String> values) {
            addCriterion("TXN_SN not in", values, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnBetween(String value1, String value2) {
            addCriterion("TXN_SN between", value1, value2, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSnNotBetween(String value1, String value2) {
            addCriterion("TXN_SN not between", value1, value2, "txnSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnIsNull() {
            addCriterion("TXN_SUB_SN is null");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnIsNotNull() {
            addCriterion("TXN_SUB_SN is not null");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnEqualTo(String value) {
            addCriterion("TXN_SUB_SN =", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnNotEqualTo(String value) {
            addCriterion("TXN_SUB_SN <>", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnGreaterThan(String value) {
            addCriterion("TXN_SUB_SN >", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_SUB_SN >=", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnLessThan(String value) {
            addCriterion("TXN_SUB_SN <", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnLessThanOrEqualTo(String value) {
            addCriterion("TXN_SUB_SN <=", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnLike(String value) {
            addCriterion("TXN_SUB_SN like", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnNotLike(String value) {
            addCriterion("TXN_SUB_SN not like", value, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnIn(List<String> values) {
            addCriterion("TXN_SUB_SN in", values, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnNotIn(List<String> values) {
            addCriterion("TXN_SUB_SN not in", values, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnBetween(String value1, String value2) {
            addCriterion("TXN_SUB_SN between", value1, value2, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnSubSnNotBetween(String value1, String value2) {
            addCriterion("TXN_SUB_SN not between", value1, value2, "txnSubSn");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNull() {
            addCriterion("TXN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andTxnDateIsNotNull() {
            addCriterion("TXN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnDateEqualTo(String value) {
            addCriterion("TXN_DATE =", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotEqualTo(String value) {
            addCriterion("TXN_DATE <>", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThan(String value) {
            addCriterion("TXN_DATE >", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_DATE >=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThan(String value) {
            addCriterion("TXN_DATE <", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLessThanOrEqualTo(String value) {
            addCriterion("TXN_DATE <=", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateLike(String value) {
            addCriterion("TXN_DATE like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotLike(String value) {
            addCriterion("TXN_DATE not like", value, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateIn(List<String> values) {
            addCriterion("TXN_DATE in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotIn(List<String> values) {
            addCriterion("TXN_DATE not in", values, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateBetween(String value1, String value2) {
            addCriterion("TXN_DATE between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnDateNotBetween(String value1, String value2) {
            addCriterion("TXN_DATE not between", value1, value2, "txnDate");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNull() {
            addCriterion("TXN_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIsNotNull() {
            addCriterion("TXN_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTxnCodeEqualTo(String value) {
            addCriterion("TXN_CODE =", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotEqualTo(String value) {
            addCriterion("TXN_CODE <>", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThan(String value) {
            addCriterion("TXN_CODE >", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TXN_CODE >=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThan(String value) {
            addCriterion("TXN_CODE <", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLessThanOrEqualTo(String value) {
            addCriterion("TXN_CODE <=", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeLike(String value) {
            addCriterion("TXN_CODE like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotLike(String value) {
            addCriterion("TXN_CODE not like", value, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeIn(List<String> values) {
            addCriterion("TXN_CODE in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotIn(List<String> values) {
            addCriterion("TXN_CODE not in", values, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeBetween(String value1, String value2) {
            addCriterion("TXN_CODE between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andTxnCodeNotBetween(String value1, String value2) {
            addCriterion("TXN_CODE not between", value1, value2, "txnCode");
            return (Criteria) this;
        }

        public Criteria andVchStsIsNull() {
            addCriterion("VCH_STS is null");
            return (Criteria) this;
        }

        public Criteria andVchStsIsNotNull() {
            addCriterion("VCH_STS is not null");
            return (Criteria) this;
        }

        public Criteria andVchStsEqualTo(String value) {
            addCriterion("VCH_STS =", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotEqualTo(String value) {
            addCriterion("VCH_STS <>", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsGreaterThan(String value) {
            addCriterion("VCH_STS >", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_STS >=", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLessThan(String value) {
            addCriterion("VCH_STS <", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLessThanOrEqualTo(String value) {
            addCriterion("VCH_STS <=", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsLike(String value) {
            addCriterion("VCH_STS like", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotLike(String value) {
            addCriterion("VCH_STS not like", value, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsIn(List<String> values) {
            addCriterion("VCH_STS in", values, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotIn(List<String> values) {
            addCriterion("VCH_STS not in", values, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsBetween(String value1, String value2) {
            addCriterion("VCH_STS between", value1, value2, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchStsNotBetween(String value1, String value2) {
            addCriterion("VCH_STS not between", value1, value2, "vchSts");
            return (Criteria) this;
        }

        public Criteria andVchTypIsNull() {
            addCriterion("VCH_TYP is null");
            return (Criteria) this;
        }

        public Criteria andVchTypIsNotNull() {
            addCriterion("VCH_TYP is not null");
            return (Criteria) this;
        }

        public Criteria andVchTypEqualTo(String value) {
            addCriterion("VCH_TYP =", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypNotEqualTo(String value) {
            addCriterion("VCH_TYP <>", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypGreaterThan(String value) {
            addCriterion("VCH_TYP >", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_TYP >=", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypLessThan(String value) {
            addCriterion("VCH_TYP <", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypLessThanOrEqualTo(String value) {
            addCriterion("VCH_TYP <=", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypLike(String value) {
            addCriterion("VCH_TYP like", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypNotLike(String value) {
            addCriterion("VCH_TYP not like", value, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypIn(List<String> values) {
            addCriterion("VCH_TYP in", values, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypNotIn(List<String> values) {
            addCriterion("VCH_TYP not in", values, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypBetween(String value1, String value2) {
            addCriterion("VCH_TYP between", value1, value2, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchTypNotBetween(String value1, String value2) {
            addCriterion("VCH_TYP not between", value1, value2, "vchTyp");
            return (Criteria) this;
        }

        public Criteria andVchNumIsNull() {
            addCriterion("VCH_NUM is null");
            return (Criteria) this;
        }

        public Criteria andVchNumIsNotNull() {
            addCriterion("VCH_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andVchNumEqualTo(String value) {
            addCriterion("VCH_NUM =", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotEqualTo(String value) {
            addCriterion("VCH_NUM <>", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumGreaterThan(String value) {
            addCriterion("VCH_NUM >", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumGreaterThanOrEqualTo(String value) {
            addCriterion("VCH_NUM >=", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLessThan(String value) {
            addCriterion("VCH_NUM <", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLessThanOrEqualTo(String value) {
            addCriterion("VCH_NUM <=", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumLike(String value) {
            addCriterion("VCH_NUM like", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotLike(String value) {
            addCriterion("VCH_NUM not like", value, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumIn(List<String> values) {
            addCriterion("VCH_NUM in", values, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotIn(List<String> values) {
            addCriterion("VCH_NUM not in", values, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumBetween(String value1, String value2) {
            addCriterion("VCH_NUM between", value1, value2, "vchNum");
            return (Criteria) this;
        }

        public Criteria andVchNumNotBetween(String value1, String value2) {
            addCriterion("VCH_NUM not between", value1, value2, "vchNum");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIsNull() {
            addCriterion("OPR1_NO is null");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIsNotNull() {
            addCriterion("OPR1_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOpr1NoEqualTo(String value) {
            addCriterion("OPR1_NO =", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotEqualTo(String value) {
            addCriterion("OPR1_NO <>", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoGreaterThan(String value) {
            addCriterion("OPR1_NO >", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoGreaterThanOrEqualTo(String value) {
            addCriterion("OPR1_NO >=", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLessThan(String value) {
            addCriterion("OPR1_NO <", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLessThanOrEqualTo(String value) {
            addCriterion("OPR1_NO <=", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoLike(String value) {
            addCriterion("OPR1_NO like", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotLike(String value) {
            addCriterion("OPR1_NO not like", value, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoIn(List<String> values) {
            addCriterion("OPR1_NO in", values, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotIn(List<String> values) {
            addCriterion("OPR1_NO not in", values, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoBetween(String value1, String value2) {
            addCriterion("OPR1_NO between", value1, value2, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr1NoNotBetween(String value1, String value2) {
            addCriterion("OPR1_NO not between", value1, value2, "opr1No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIsNull() {
            addCriterion("OPR2_NO is null");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIsNotNull() {
            addCriterion("OPR2_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOpr2NoEqualTo(String value) {
            addCriterion("OPR2_NO =", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotEqualTo(String value) {
            addCriterion("OPR2_NO <>", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoGreaterThan(String value) {
            addCriterion("OPR2_NO >", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoGreaterThanOrEqualTo(String value) {
            addCriterion("OPR2_NO >=", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLessThan(String value) {
            addCriterion("OPR2_NO <", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLessThanOrEqualTo(String value) {
            addCriterion("OPR2_NO <=", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoLike(String value) {
            addCriterion("OPR2_NO like", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotLike(String value) {
            addCriterion("OPR2_NO not like", value, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoIn(List<String> values) {
            addCriterion("OPR2_NO in", values, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotIn(List<String> values) {
            addCriterion("OPR2_NO not in", values, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoBetween(String value1, String value2) {
            addCriterion("OPR2_NO between", value1, value2, "opr2No");
            return (Criteria) this;
        }

        public Criteria andOpr2NoNotBetween(String value1, String value2) {
            addCriterion("OPR2_NO not between", value1, value2, "opr2No");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnIsNull() {
            addCriterion("CBS_TXN_SN is null");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnIsNotNull() {
            addCriterion("CBS_TXN_SN is not null");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnEqualTo(String value) {
            addCriterion("CBS_TXN_SN =", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnNotEqualTo(String value) {
            addCriterion("CBS_TXN_SN <>", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnGreaterThan(String value) {
            addCriterion("CBS_TXN_SN >", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnGreaterThanOrEqualTo(String value) {
            addCriterion("CBS_TXN_SN >=", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnLessThan(String value) {
            addCriterion("CBS_TXN_SN <", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnLessThanOrEqualTo(String value) {
            addCriterion("CBS_TXN_SN <=", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnLike(String value) {
            addCriterion("CBS_TXN_SN like", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnNotLike(String value) {
            addCriterion("CBS_TXN_SN not like", value, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnIn(List<String> values) {
            addCriterion("CBS_TXN_SN in", values, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnNotIn(List<String> values) {
            addCriterion("CBS_TXN_SN not in", values, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnBetween(String value1, String value2) {
            addCriterion("CBS_TXN_SN between", value1, value2, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andCbsTxnSnNotBetween(String value1, String value2) {
            addCriterion("CBS_TXN_SN not between", value1, value2, "cbsTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnIsNull() {
            addCriterion("FUND_TXN_SN is null");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnIsNotNull() {
            addCriterion("FUND_TXN_SN is not null");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnEqualTo(String value) {
            addCriterion("FUND_TXN_SN =", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnNotEqualTo(String value) {
            addCriterion("FUND_TXN_SN <>", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnGreaterThan(String value) {
            addCriterion("FUND_TXN_SN >", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnGreaterThanOrEqualTo(String value) {
            addCriterion("FUND_TXN_SN >=", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnLessThan(String value) {
            addCriterion("FUND_TXN_SN <", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnLessThanOrEqualTo(String value) {
            addCriterion("FUND_TXN_SN <=", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnLike(String value) {
            addCriterion("FUND_TXN_SN like", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnNotLike(String value) {
            addCriterion("FUND_TXN_SN not like", value, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnIn(List<String> values) {
            addCriterion("FUND_TXN_SN in", values, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnNotIn(List<String> values) {
            addCriterion("FUND_TXN_SN not in", values, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnBetween(String value1, String value2) {
            addCriterion("FUND_TXN_SN between", value1, value2, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andFundTxnSnNotBetween(String value1, String value2) {
            addCriterion("FUND_TXN_SN not between", value1, value2, "fundTxnSn");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 12 22:37:59 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}