package common.repository.hmfs.model;

public class TxnVouchLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.PKID
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String txnSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.TXN_SUB_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String txnSubSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.TXN_CODE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String txnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.VCH_STS
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String vchSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.VCH_TYP
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String vchTyp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.VCH_NUM
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String vchNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.OPR1_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String opr1No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.OPR2_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String opr2No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.CBS_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String cbsTxnSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.FUND_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String fundTxnSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.TXN_VOUCH_LOG.REMARK
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.PKID
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.PKID
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.PKID
     *
     * @param pkid the value for HMFS.TXN_VOUCH_LOG.PKID
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.TXN_SN
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getTxnSn() {
        return txnSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.TXN_SN
     *
     * @param txnSn the value for HMFS.TXN_VOUCH_LOG.TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setTxnSn(String txnSn) {
        this.txnSn = txnSn == null ? null : txnSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.TXN_SUB_SN
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.TXN_SUB_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getTxnSubSn() {
        return txnSubSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.TXN_SUB_SN
     *
     * @param txnSubSn the value for HMFS.TXN_VOUCH_LOG.TXN_SUB_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setTxnSubSn(String txnSubSn) {
        this.txnSubSn = txnSubSn == null ? null : txnSubSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.TXN_DATE
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.TXN_DATE
     *
     * @param txnDate the value for HMFS.TXN_VOUCH_LOG.TXN_DATE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.TXN_CODE
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.TXN_CODE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getTxnCode() {
        return txnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.TXN_CODE
     *
     * @param txnCode the value for HMFS.TXN_VOUCH_LOG.TXN_CODE
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setTxnCode(String txnCode) {
        this.txnCode = txnCode == null ? null : txnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.VCH_STS
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.VCH_STS
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getVchSts() {
        return vchSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.VCH_STS
     *
     * @param vchSts the value for HMFS.TXN_VOUCH_LOG.VCH_STS
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setVchSts(String vchSts) {
        this.vchSts = vchSts == null ? null : vchSts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.VCH_TYP
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.VCH_TYP
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getVchTyp() {
        return vchTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.VCH_TYP
     *
     * @param vchTyp the value for HMFS.TXN_VOUCH_LOG.VCH_TYP
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setVchTyp(String vchTyp) {
        this.vchTyp = vchTyp == null ? null : vchTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.VCH_NUM
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.VCH_NUM
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getVchNum() {
        return vchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.VCH_NUM
     *
     * @param vchNum the value for HMFS.TXN_VOUCH_LOG.VCH_NUM
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setVchNum(String vchNum) {
        this.vchNum = vchNum == null ? null : vchNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.OPR1_NO
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.OPR1_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getOpr1No() {
        return opr1No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.OPR1_NO
     *
     * @param opr1No the value for HMFS.TXN_VOUCH_LOG.OPR1_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setOpr1No(String opr1No) {
        this.opr1No = opr1No == null ? null : opr1No.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.OPR2_NO
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.OPR2_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getOpr2No() {
        return opr2No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.OPR2_NO
     *
     * @param opr2No the value for HMFS.TXN_VOUCH_LOG.OPR2_NO
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setOpr2No(String opr2No) {
        this.opr2No = opr2No == null ? null : opr2No.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.CBS_TXN_SN
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.CBS_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getCbsTxnSn() {
        return cbsTxnSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.CBS_TXN_SN
     *
     * @param cbsTxnSn the value for HMFS.TXN_VOUCH_LOG.CBS_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setCbsTxnSn(String cbsTxnSn) {
        this.cbsTxnSn = cbsTxnSn == null ? null : cbsTxnSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.FUND_TXN_SN
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.FUND_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getFundTxnSn() {
        return fundTxnSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.FUND_TXN_SN
     *
     * @param fundTxnSn the value for HMFS.TXN_VOUCH_LOG.FUND_TXN_SN
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setFundTxnSn(String fundTxnSn) {
        this.fundTxnSn = fundTxnSn == null ? null : fundTxnSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.TXN_VOUCH_LOG.REMARK
     *
     * @return the value of HMFS.TXN_VOUCH_LOG.REMARK
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.TXN_VOUCH_LOG.REMARK
     *
     * @param remark the value for HMFS.TXN_VOUCH_LOG.REMARK
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}