package common.repository.hmfs.dao;

import common.repository.hmfs.model.HisFcjMsgoutLog;
import common.repository.hmfs.model.HisFcjMsgoutLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HisFcjMsgoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int countByExample(HisFcjMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int deleteByExample(HisFcjMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int insert(HisFcjMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int insertSelective(HisFcjMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    List<HisFcjMsgoutLog> selectByExample(HisFcjMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    HisFcjMsgoutLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int updateByExampleSelective(@Param("record") HisFcjMsgoutLog record, @Param("example") HisFcjMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int updateByExample(@Param("record") HisFcjMsgoutLog record, @Param("example") HisFcjMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int updateByPrimaryKeySelective(HisFcjMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_FCJ_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 08 11:26:04 CST 2012
     */
    int updateByPrimaryKey(HisFcjMsgoutLog record);
}