package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmActinfoCbs;
import common.repository.hmfs.model.HmActinfoCbsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HmActinfoCbsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int countByExample(HmActinfoCbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int deleteByExample(HmActinfoCbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int insert(HmActinfoCbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int insertSelective(HmActinfoCbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    List<HmActinfoCbs> selectByExample(HmActinfoCbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    HmActinfoCbs selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmActinfoCbs record, @Param("example") HmActinfoCbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int updateByExample(@Param("record") HmActinfoCbs record, @Param("example") HmActinfoCbsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int updateByPrimaryKeySelective(HmActinfoCbs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACTINFO_CBS
     *
     * @mbggenerated Fri Mar 09 18:48:45 CST 2012
     */
    int updateByPrimaryKey(HmActinfoCbs record);
}