package common.repository.hmfs.dao;

import common.repository.hmfs.model.BkCmbDept;
import common.repository.hmfs.model.BkCmbDeptExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface BkCmbDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int countByExample(BkCmbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int deleteByExample(BkCmbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int insert(BkCmbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int insertSelective(BkCmbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    List<BkCmbDept> selectByExample(BkCmbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    BkCmbDept selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int updateByExampleSelective(@Param("record") BkCmbDept record, @Param("example") BkCmbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int updateByExample(@Param("record") BkCmbDept record, @Param("example") BkCmbDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int updateByPrimaryKeySelective(BkCmbDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.BK_CMB_DEPT
     *
     * @mbggenerated Mon Aug 20 10:03:20 CST 2012
     */
    int updateByPrimaryKey(BkCmbDept record);
}