package common.repository.hmfs.dao;

import common.repository.hmfs.model.HisMsgoutLog;
import common.repository.hmfs.model.HisMsgoutLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HisMsgoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int countByExample(HisMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int deleteByExample(HisMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int insert(HisMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int insertSelective(HisMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    List<HisMsgoutLog> selectByExample(HisMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    HisMsgoutLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByExampleSelective(@Param("record") HisMsgoutLog record, @Param("example") HisMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByExample(@Param("record") HisMsgoutLog record, @Param("example") HisMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByPrimaryKeySelective(HisMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByPrimaryKey(HisMsgoutLog record);
}