package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmActFundDel;
import common.repository.hmfs.model.HmActFundDelExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmActFundDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int countByExample(HmActFundDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int deleteByExample(HmActFundDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int insert(HmActFundDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int insertSelective(HmActFundDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    List<HmActFundDel> selectByExample(HmActFundDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    HmActFundDel selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmActFundDel record, @Param("example") HmActFundDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int updateByExample(@Param("record") HmActFundDel record, @Param("example") HmActFundDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int updateByPrimaryKeySelective(HmActFundDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_ACT_FUND_DEL
     *
     * @mbggenerated Tue Jul 17 10:02:16 CST 2012
     */
    int updateByPrimaryKey(HmActFundDel record);
}