package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmChkLog;
import common.repository.hmfs.model.HmChkLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmChkLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int countByExample(HmChkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int deleteByExample(HmChkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int insert(HmChkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int insertSelective(HmChkLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    List<HmChkLog> selectByExample(HmChkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmChkLog record, @Param("example") HmChkLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int updateByExample(@Param("record") HmChkLog record, @Param("example") HmChkLogExample example);
}