package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmChkAct;
import common.repository.hmfs.model.HmChkActExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmChkActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int countByExample(HmChkActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int deleteByExample(HmChkActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int insert(HmChkAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int insertSelective(HmChkAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    List<HmChkAct> selectByExample(HmChkActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    HmChkAct selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmChkAct record, @Param("example") HmChkActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int updateByExample(@Param("record") HmChkAct record, @Param("example") HmChkActExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int updateByPrimaryKeySelective(HmChkAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_ACT
     *
     * @mbggenerated Tue Jul 10 17:21:41 CST 2012
     */
    int updateByPrimaryKey(HmChkAct record);
}