package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmChkTxn;
import common.repository.hmfs.model.HmChkTxnExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmChkTxnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int countByExample(HmChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int deleteByExample(HmChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int insert(HmChkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int insertSelective(HmChkTxn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    List<HmChkTxn> selectByExample(HmChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmChkTxn record, @Param("example") HmChkTxnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_CHK_LOG
     *
     * @mbggenerated Wed Mar 14 09:21:32 CST 2012
     */
    int updateByExample(@Param("record") HmChkTxn record, @Param("example") HmChkTxnExample example);
}