package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmMsgOut;
import common.repository.hmfs.model.HmMsgOutExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmMsgOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int countByExample(HmMsgOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int deleteByExample(HmMsgOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int insert(HmMsgOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int insertSelective(HmMsgOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    List<HmMsgOut> selectByExample(HmMsgOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    HmMsgOut selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmMsgOut record, @Param("example") HmMsgOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByExample(@Param("record") HmMsgOut record, @Param("example") HmMsgOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByPrimaryKeySelective(HmMsgOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HIS_MSGOUT_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByPrimaryKey(HmMsgOut record);
}