package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmSct;
import common.repository.hmfs.model.HmSctExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmSctMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int countByExample(HmSctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int deleteByExample(HmSctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int deleteByPrimaryKey(String sctSeqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int insert(HmSct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int insertSelective(HmSct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    List<HmSct> selectByExample(HmSctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    HmSct selectByPrimaryKey(String sctSeqno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmSct record, @Param("example") HmSctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int updateByExample(@Param("record") HmSct record, @Param("example") HmSctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int updateByPrimaryKeySelective(HmSct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_SCT
     *
     * @mbggenerated Mon Mar 12 21:59:23 CST 2012
     */
    int updateByPrimaryKey(HmSct record);
}