package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnVch;
import common.repository.hmfs.model.HmTxnVchExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnVchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int countByExample(HmTxnVchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int deleteByExample(HmTxnVchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int insert(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int insertSelective(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    List<HmTxnVch> selectByExample(HmTxnVchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    HmTxnVch selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnVch record, @Param("example") HmTxnVchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int updateByExample(@Param("record") HmTxnVch record, @Param("example") HmTxnVchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int updateByPrimaryKeySelective(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_VCH
     *
     * @mbggenerated Sun Mar 25 21:56:37 CST 2012
     */
    int updateByPrimaryKey(HmTxnVch record);
}