package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnStl;
import common.repository.hmfs.model.HmTxnStlExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnStlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int countByExample(HmTxnStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int deleteByExample(HmTxnStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int insert(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int insertSelective(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    List<HmTxnStl> selectByExample(HmTxnStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    HmTxnStl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnStl record, @Param("example") HmTxnStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int updateByExample(@Param("record") HmTxnStl record, @Param("example") HmTxnStlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int updateByPrimaryKeySelective(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL
     *
     * @mbggenerated Sun Mar 25 09:56:53 CST 2012
     */
    int updateByPrimaryKey(HmTxnStl record);


    @Select(" select t.cbs_actno as cbsActno, t.txn_sn as txnSn,t.cbs_txn_sn as cbsTxnSn,sum(t.txn_amt) txnAmt," +
            " txn_date as txnDate,t.dc_flag as dcFlag from HM_TXN_STL t " +
            " group by t.cbs_actno, t.txn_sn,t.cbs_txn_sn,txn_date,t.dc_flag " +
            " having t.txn_date in #{date} " +
            " order by t.cbs_txn_sn")
    List<HmTxnStl> qryHmTxnStlForChkAct(@Param("date")String date);
}