package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnStl;
import common.repository.hmfs.model.HmTxnStlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnStlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int countByExample(HmTxnStlExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int deleteByExample(HmTxnStlExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int insert(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int insertSelective(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    List<HmTxnStl> selectByExample(HmTxnStlExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    HmTxnStl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnStl record, @Param("exampleHm") HmTxnStlExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByExample(@Param("record") HmTxnStl record, @Param("exampleHm") HmTxnStlExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByPrimaryKeySelective(HmTxnStl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_CBS_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByPrimaryKey(HmTxnStl record);
}