package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnVch;
import common.repository.hmfs.model.HmTxnVchExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnVchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int countByExample(HmTxnVchExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int deleteByExample(HmTxnVchExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int insert(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int insertSelective(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    List<HmTxnVch> selectByExample(HmTxnVchExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    HmTxnVch selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnVch record, @Param("exampleHm") HmTxnVchExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int updateByExample(@Param("record") HmTxnVch record, @Param("exampleHm") HmTxnVchExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int updateByPrimaryKeySelective(HmTxnVch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_VOUCH_LOG
     *
     * @mbggenerated Mon Mar 12 22:37:59 CST 2012
     */
    int updateByPrimaryKey(HmTxnVch record);
}