package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnFund;
import common.repository.hmfs.model.HmTxnFundExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnFundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int countByExample(HmTxnFundExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int deleteByExample(HmTxnFundExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int insert(HmTxnFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int insertSelective(HmTxnFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    List<HmTxnFund> selectByExample(HmTxnFundExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    HmTxnFund selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnFund record, @Param("exampleHm") HmTxnFundExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByExample(@Param("record") HmTxnFund record, @Param("exampleHm") HmTxnFundExample exampleHm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByPrimaryKeySelective(HmTxnFund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 22:29:19 CST 2012
     */
    int updateByPrimaryKey(HmTxnFund record);
}