package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmTxnStlDbl;
import common.repository.hmfs.model.HmTxnStlDblExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HmTxnStlDblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int countByExample(HmTxnStlDblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int deleteByExample(HmTxnStlDblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int insert(HmTxnStlDbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int insertSelective(HmTxnStlDbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    List<HmTxnStlDbl> selectByExample(HmTxnStlDblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int updateByExampleSelective(@Param("record") HmTxnStlDbl record, @Param("example") HmTxnStlDblExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_TXN_STL_DBL
     *
     * @mbggenerated Mon Aug 13 14:15:23 CST 2012
     */
    int updateByExample(@Param("record") HmTxnStlDbl record, @Param("example") HmTxnStlDblExample example);
}