package common.repository.hmfs.dao;

import common.repository.hmfs.model.HmVchJrnl;
import common.repository.hmfs.model.HmVchJrnlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface HmVchJrnlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int countByExample(HmVchJrnlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int deleteByExample(HmVchJrnlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int insert(HmVchJrnl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int insertSelective(HmVchJrnl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    List<HmVchJrnl> selectByExample(HmVchJrnlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    HmVchJrnl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") HmVchJrnl record, @Param("example") HmVchJrnlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int updateByExample(@Param("record") HmVchJrnl record, @Param("example") HmVchJrnlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int updateByPrimaryKeySelective(HmVchJrnl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.HM_VCH_JRNL
     *
     * @mbggenerated Wed May 13 18:53:12 CST 2015
     */
    int updateByPrimaryKey(HmVchJrnl record);
}