package common.repository.hmfs.dao;

import common.repository.hmfs.model.TmpMsgoutLog;
import common.repository.hmfs.model.TmpMsgoutLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TmpMsgoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int countByExample(TmpMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int deleteByExample(TmpMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int insert(TmpMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int insertSelective(TmpMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    List<TmpMsgoutLog> selectByExample(TmpMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    TmpMsgoutLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int updateByExampleSelective(@Param("record") TmpMsgoutLog record, @Param("example") TmpMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int updateByExample(@Param("record") TmpMsgoutLog record, @Param("example") TmpMsgoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int updateByPrimaryKeySelective(TmpMsgoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGOUT_LOG
     *
     * @mbggenerated Sun Mar 18 13:10:26 CST 2012
     */
    int updateByPrimaryKey(TmpMsgoutLog record);
}