package common.repository.hmfs.dao;

import common.repository.hmfs.model.TmpMsgIn;
import common.repository.hmfs.model.TmpMsgInExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TmpMsgInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int countByExample(TmpMsgInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int deleteByExample(TmpMsgInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int insert(TmpMsgIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int insertSelective(TmpMsgIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    List<TmpMsgIn> selectByExample(TmpMsgInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int updateByExampleSelective(@Param("record") TmpMsgIn record, @Param("example") TmpMsgInExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSG_IN
     *
     * @mbggenerated Sun Mar 25 21:53:14 CST 2012
     */
    int updateByExample(@Param("record") TmpMsgIn record, @Param("example") TmpMsgInExample example);
}