package common.repository.hmfs.dao;

import common.repository.hmfs.model.TmpMsginLog;
import common.repository.hmfs.model.TmpMsginLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TmpMsginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int countByExample(TmpMsginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int deleteByExample(TmpMsginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int insert(TmpMsginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int insertSelective(TmpMsginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    List<TmpMsginLog> selectByExample(TmpMsginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByExampleSelective(@Param("record") TmpMsginLog record, @Param("example") TmpMsginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TMP_MSGIN_LOG
     *
     * @mbggenerated Thu Mar 15 21:49:57 CST 2012
     */
    int updateByExample(@Param("record") TmpMsginLog record, @Param("example") TmpMsginLogExample example);
}