package common.repository.hmfs.dao;

import common.repository.hmfs.model.TxnFundLog;
import common.repository.hmfs.model.TxnFundLogExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TxnFundLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int countByExample(TxnFundLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int deleteByExample(TxnFundLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int insert(TxnFundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int insertSelective(TxnFundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    List<TxnFundLog> selectByExample(TxnFundLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    TxnFundLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByExampleSelective(@Param("record") TxnFundLog record, @Param("example") TxnFundLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByExample(@Param("record") TxnFundLog record, @Param("example") TxnFundLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByPrimaryKeySelective(TxnFundLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HMFS.TXN_FUND_LOG
     *
     * @mbggenerated Sun Mar 11 17:39:32 CST 2012
     */
    int updateByPrimaryKey(TxnFundLog record);
}