package common.repository.hmfs.model;

import java.math.BigDecimal;

public class HmChkAct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String txnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String sendSysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String actno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private BigDecimal actbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    private String chksts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.PKID
     *
     * @return the value of HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.PKID
     *
     * @param pkid the value for HMFS.HM_CHK_ACT.PKID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @return the value of HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getTxnDate() {
        return txnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @param txnDate the value for HMFS.HM_CHK_ACT.TXN_DATE
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setTxnDate(String txnDate) {
        this.txnDate = txnDate == null ? null : txnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @return the value of HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getSendSysId() {
        return sendSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @param sendSysId the value for HMFS.HM_CHK_ACT.SEND_SYS_ID
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setSendSysId(String sendSysId) {
        this.sendSysId = sendSysId == null ? null : sendSysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @return the value of HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getActno() {
        return actno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.ACTNO
     *
     * @param actno the value for HMFS.HM_CHK_ACT.ACTNO
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setActno(String actno) {
        this.actno = actno == null ? null : actno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @return the value of HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public BigDecimal getActbal() {
        return actbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.ACTBAL
     *
     * @param actbal the value for HMFS.HM_CHK_ACT.ACTBAL
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setActbal(BigDecimal actbal) {
        this.actbal = actbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @return the value of HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public String getChksts() {
        return chksts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HMFS.HM_CHK_ACT.CHKSTS
     *
     * @param chksts the value for HMFS.HM_CHK_ACT.CHKSTS
     *
     * @mbggenerated Sat Mar 24 20:15:49 CST 2012
     */
    public void setChksts(String chksts) {
        this.chksts = chksts == null ? null : chksts.trim();
    }
}